apiVersion: apps/v1
kind: Deployement
metadata:
     name: mederp
     labels: 
         app: mederp
spe:
   replicas: 4
   selector:
     matchLabels:
     app: mederp
   strategy:
        type : RollingUpdate
        maxSurge: 1
        maxUnavailable: 1
   template: 
     metadata:
     name: mederp
     labels: 
         app: mederp
     spec:
        containers:
        - name: http
          image: nginx
          ports:
          - name: http
          containerPort: 80
          protocol: TCP


            
