apiVersion: v1
kind: Pod
metadata:   
    name: nginxpod
spec:
   volumes:
      - name: mypd
        persistentVolumeClaim:
            claimName: pv-claim
   containers:
      - image: nginx:latest
        ports:
            - containerPort: 80
        name: nginxcont
        volumeMounts:
            - mountPath: "/etc/passwd"
              name: mypd

