apiVersion: v1
kind:  PersistentVolume
metadata:
    name: pv-volume
    labels:
        app: pv
spec:
    storageClassName: standard
    volumeMode: filesystem
    accessMode:
      - ReadWriteOnce
    capacity:
      storage: 10Gi
    persistentvolumeclaimPolicy: Recycle
    hostPath:
      path: "/mnt/data"   
          

