apiVersion:  apps/v1
kind: Daemonset
metadata:
    name: cwgagent
    labels:
      app: cwgagent
spec:
    selector:
        matchLabels:
            app: cwgagent
    template:
        metadata:
        name: cwgagent
    labels:
      app: cwgagent
    spec:
        containers:
          - name: nginx
            image: amazon/cloudwatch-agent
            ports:
            - containerPort: 80
