apiVersion: v1
kind: Pod
metadata:   
    name: cipod3
    namespace: meshoo
    labels:
       app: cipod3
spec:
   containers:
      - image: nginx:latest
        ports:
            - containerPort: 80
        name: nginxcont

---
apiVersion: v1
kind: Service
metadata:
   name: ciservice3
   namespace: meshoo
spec:
  selector:
     app: cipod3
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP


