apiVersion: v1
kind: Pod
metadata:   
    name: cipod2
    namespace: flipkart
    labels:
       app: cipod2
spec:
   containers:
      - image: nginx:latest
        ports:
            - containerPort: 80
        name: nginxcont

---
apiVersion: v1
kind: Service
metadata:
   name: ciservice2
   namespace: flipkart
spec:
  selector:
     app: cipod2
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP


