apiVersion: v1 
kind: Service
metadata: 
   name: npci
   labels: 
        app: npci
spec:
  selector:
     app: nginx
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 